atabases:
 - name: friends
   databaseName: friends
   user: friends

services:
 - type: web
   name: friends
   env: ruby
   buildCommand: "./bin/render-build.sh"
   startCommand: "bundle exec puma -C config/puma.rb"
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: friends
         property: connectionString
     - key: RAILS_MASTER_KEY
       sync: false